/*
 * generated by Xtext
 */
package jpadsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JPADslUiModule extends jpadsl.ui.AbstractJPADslUiModule {
	public JPADslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
