/*
 * generated by Xtext
 */
package workflowdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WorkflowDslRuntimeModule extends workflowdsl.AbstractWorkflowDslRuntimeModule {

}
