/*
 * generated by Xtext
 */
package accessdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AccessDslUiModule extends accessdsl.ui.AbstractAccessDslUiModule {
	public AccessDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
