/*
 * generated by Xtext
 */
package jpadsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JPADslRuntimeModule extends jpadsl.AbstractJPADslRuntimeModule {

}
