/*
* generated by Xtext
*/
package accessdsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AccessDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return accessdsl.ui.internal.AccessDslActivator.getInstance().getInjector("accessdsl.AccessDsl");
	}
	
}
