/*
 * generated by Xtext
 */
package jpaqldsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JPAQLDslUiModule extends jpaqldsl.ui.AbstractJPAQLDslUiModule {
	public JPAQLDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
