/*
 * generated by Xtext
 */
package jpaqldsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JPAQLDslRuntimeModule extends jpaqldsl.AbstractJPAQLDslRuntimeModule {

}
