/*
* generated by Xtext
*/
package jpadsl.ui.contentassist;

import jpadsl.ui.contentassist.AbstractJPADslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JPADslProposalProvider extends AbstractJPADslProposalProvider {

}
