/*
* generated by Xtext
*/
package jpadsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class JPADslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return jpadsl.ui.internal.JPADslActivator.getInstance().getInjector("jpadsl.JPADsl");
	}
	
}
