/*
 * generated by Xtext
 */
package jpadsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import jpadsl.ui.internal.JPADslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JPADslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return JPADslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return JPADslActivator.getInstance().getInjector(JPADslActivator.JPADSL_JPADSL);
	}
	
}
