/*
 * generated by Xtext
 */
package workflowdsl.ui.contentassist

import workflowdsl.ui.contentassist.AbstractWorkflowDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class WorkflowDslProposalProvider extends AbstractWorkflowDslProposalProvider {
}
