/*
* generated by Xtext
*/
package workflowdsl.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class WorkflowDslProposalProvider extends workflowdsl.ui.contentassist.AbstractWorkflowDslProposalProvider {

}
