/*
* generated by Xtext
*/
package jpaqldsl.ui.contentassist;

import jpaqldsl.ui.contentassist.AbstractJPAQLDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JPAQLDslProposalProvider extends AbstractJPAQLDslProposalProvider {

}
