/*
* generated by Xtext
*/
package jpaqldsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class JPAQLDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return jpaqldsl.ui.internal.JPAQLDslActivator.getInstance().getInjector("jpaqldsl.JPAQLDsl");
	}
	
}
