/*
 * generated by Xtext
 */
package workflowdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WorkflowDslUiModule extends workflowdsl.ui.AbstractWorkflowDslUiModule {
	public WorkflowDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
