/*
* generated by Xtext
*/
package accessdsl.ui.contentassist;

import accessdsl.ui.contentassist.AbstractAccessDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AccessDslProposalProvider extends AbstractAccessDslProposalProvider {

}
