/*
 * generated by Xtext
 */
package jpaqldsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import jpaqldsl.ui.internal.JPAQLDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JPAQLDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return JPAQLDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return JPAQLDslActivator.getInstance().getInjector(JPAQLDslActivator.JPAQLDSL_JPAQLDSL);
	}
	
}
