/*
 * generated by Xtext
 */
package accessdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AccessDslRuntimeModule extends accessdsl.AbstractAccessDslRuntimeModule {

}
